---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by synodriver.
--- DateTime: 2022/7/1 20:38
---

hfm = require("hfm")

data = "1234"

for i=1,10 do
    data = data..data
end
print("origin len : "..#data)
encoded = hfm.encode(data)
print("encoded len : "..#encoded)
print(hfm.decode(encoded))